baseURL = 'https://kawoosique.com/'
languageCode = 'ru-ru'
title = 'Блог KAWOOSIQUE'
theme = 'PaperMod'
[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    # Общие настройки темы
    env = 'production'
    title = 'KAWOOSIQUE'
    description = 'Мир сквозь фильтр кофе'
    author = 'Vakhnovsky'
    
    # Включаем красивую кнопку переключения темная/светлая тема
    defaultTheme = 'auto'
    disableThemeToggle = false
    
    # Показываем код языка (ru) и иконку RSS
    ShowShareButtons = false # выключим лишний мусор под постами
    ShowReadingTime = true # показывать время чтения статьи
    ShowCodeCopyButtons = true # кнопка "скопировать" для блоков кода
    
    [params.label]
    text = "" # Оставляем пустым, чтобы текст не дублировал графику
    icon = "/main_logo.svg" # Путь к горизонтальному логотипу в шапке
    iconHeight = 35 # Высота логотипа в пикселях (можно отрегулировать под себя)

    # Настройка Главной страницы (Режим Профиля)
    [params.profileMode]
        enabled = true
        title = 'KAWOOSIQUE'
        subtitle = 'Мир сквозь фильтр кофе'
        imageUrl = '/sq_logo.svg' # Сюда мы позже подставим твою реальную аватарку
        imageWidth = 150
        imageHeight = 150
        imageTitle = 'KAWOOSIQUE'
        
        # Кнопки-ссылки под твоим описанием
        [[params.profileMode.buttons]]
            name = '📚 Все посты'
            url = 'posts/'
        [[params.profileMode.buttons]]
            name = '✈️ Мой Telegram'
            url = 'https://t.me/kawoosique' # Поменяй на свой юзернейм

    # Иконки соцсетей (появятся в самом низу)
    [[params.socialIcons]]
        name = 'telegram'
        url = 'https://t.me/kawoosique'

# Настройка меню навигации в шапке сайта
[[menu.main]]
    name = 'Посты'
    url = 'posts/'
    weight = 10
[[menu.main]]
    name = 'Теги'
    url = 'tags/'
    weight = 20
[[menu.main]]
    name = '🔍 Поиск'
    url = 'search/'
    weight = 30
[[menu.main]]
    name = '📅 Архив'
    url = 'archives/'
    weight = 40