baseURL = 'https://kawoosique.com/'
languageCode = 'ru-ru'
title = 'KAWOOSIQUE'
theme = 'PaperMod'
buildFuture = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    # Общие настройки темы
    env = 'production'
    title = 'KAWOOSIQUE'
    # description убираем из params, чтобы не дублировать текст на главной
    author = 'Vakhnovsky'
    
    # Темы и переключатели
    defaultTheme = 'auto'
    disableThemeToggle = false
    
    # Настройки отображения элементов
    ShowShareButtons = false 
    ShowReadingTime = true 
    ShowCodeCopyButtons = true 
    # Отключаем дефолтный подвал PaperMod (Powered by Hugo & PaperMod)
    disableSpecial1stPost = false
    disableScrollToTop = false
    hideFooter = false # Скрывает/показывает копирайт и системные подписи в самом низу

    [params.label]
        text = " " 
        icon = "/main_logo.svg" 
        iconHeight = 45 

    # Настройка Главной страницы (Режим Профиля)
    [params.profileMode]
        enabled = true
        title = ' ' # Стираем текстовый заголовок, у нас уже есть логотип на аватарке!
        subtitle = ' ' # Оставляем только твой слоган
        imageUrl = '/sq_logo.svg' 
        imageWidth = 250
        imageHeight = 250
        imageTitle = 'KAWOOSIQUE'
        
        # Кнопки-ссылки
        [[params.profileMode.buttons]]
            name = 'Читать публикации'
            url = 'posts/'
        [[params.profileMode.buttons]]
            name = 'Telegram-канал'
            url = 'https://t.me/kawoosique'

    # Блок [[params.socialIcons]] полностью удалён, чтобы убрать лишний самолётик

# Настройка меню навигации в шапке сайта
[[menu.main]]
    name = 'Посты'
    url = 'posts/'
    weight = 10
[[menu.main]]
    name = 'Теги'
    url = 'tags/'
    weight = 20
[[menu.main]]
    name = 'Поиск'
    url = 'search/'
    weight = 30
[[menu.main]]
    name = 'Архив'
    url = 'archives/'
    weight = 40
